In [53]:
import torch

In [2]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

Each of these values is called an element of the tensor. The tensor x contains 12 elements.


In [3]:
x.shape

torch.Size([12])

In [4]:
# the total number of elements via numel method
x.numel()

12

In [5]:
x.shape # he shape contains just a single element and is identical to the size

torch.Size([12])

We can change the shape of a tensor without altering its size or values, by invoking reshape.

In [6]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [7]:
# a tensor with all elements set to 0 and a shape of (2, 3, 4)
torch.zeros(2, 3, 4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
# create a tensor with all 1
torch.ones(2, 3, 4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [9]:
torch.randn(3, 4)

tensor([[ 8.3655e-02,  5.0784e-01, -6.5562e-02, -9.7550e-04],
        [-1.0781e+00, -1.7803e+00,  2.6340e-02, -1.0990e+00],
        [-5.3214e-01, -1.2674e+00,  5.1707e-01, -3.6770e-01]])

In [10]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

# Indexing and Slicing

In [11]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [12]:
# slicing (e.g., X[start:stop]) where the returned value includes the first index (start) but not the last (stop).
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [13]:
# we can also write elements of a matrix by specifying indices.
X[1, 2] = 17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [14]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])

x + y, x - y, x * y, x / y, x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [15]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
print(X)
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(Y)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])


dim нь tensor-ийн аль хэмжээсийн дагуу үйлдэл хийхийг заана.

2 хэмжээст tensor-ийн хувьд:
| `dim`   | Хэмжээс        | Утга                        |
| ------- | -------------- | --------------------------- |
| `dim=0` | Мөрийн хэмжээ  | Дээрээс доош залгана        |
| `dim=1` | Баганын хэмжээ | Зүүнээс баруун тийш залгана |


In [16]:
# мөрөөр нь нийлүүлэх. when dim=0: (3,4)+(3,4) -> (6,4)
torch.cat((X, Y), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [17]:
# баганаар нь нийлүүлэх. When dim=1: (3,4)+(3,4) -> ​(3,8)
torch.cat((X, Y), dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [18]:
# For each position i, j, if X[i, j] and Y[i, j] are equal,
print(X)
print(Y)
X == Y

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])


tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [19]:
# Summing all the elements in the tensor
X.sum()

tensor(66.)

# Broadcasting

In [20]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [21]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

# Linear Algebra



## Scalar

Scalars are implemented as tensors that contain only one element.

In [22]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

## Vectors

For current purposes, you can think of a vector as a fixed-length array of scalars. As with their code counterparts, we call these scalars the elements of the vector (synonyms include entries and components).

In [23]:
x = torch.arange(3)
x

tensor([0, 1, 2])

In [24]:
x[2]

tensor(2)

In [25]:
len(x)

3

In [26]:
x.shape

torch.Size([3])

## Matrices


In [27]:
A = torch.arange(6).reshape(3, 2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

When we exchange a matrix’s rows and columns, the result is called its transpose.

In [28]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

## Tensor

In [29]:
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [30]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()  # Assign a copy of A to B by allocating new memory
print(A)
print(B)
print("Element wise addition\n", A + B)
print("Element wise product\n", A * B)

tensor([[0., 1., 2.],
        [3., 4., 5.]])
tensor([[0., 1., 2.],
        [3., 4., 5.]])
Element wise addition
 tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]])
Element wise product
 tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])


In [31]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
print(X)
print("====")
print(a + X)
print("====")
print(a * X)
print("====")
print((a * X).shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
====
tensor([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],

        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]])
====
tensor([[[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22]],

        [[24, 26, 28, 30],
         [32, 34, 36, 38],
         [40, 42, 44, 46]]])
====
torch.Size([2, 3, 4])


## Reduction

In [32]:
x = torch.arange(3, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

In [33]:
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [34]:
A.shape, A.sum()

(torch.Size([2, 3]), tensor(15.))

In [35]:
A.shape, A.sum(axis=1).shape

(torch.Size([2, 3]), torch.Size([2]))

In [36]:
A.sum(axis=[0, 1]) == A.sum()

tensor(True)

## Dot Products


In [40]:
y = torch.ones(3, dtype=torch.float32)
print(f"x: {x}")
print(f"y: {y}")

print(f"dot product of x and y: {torch.dot(x, y)}")

x: tensor([0., 1., 2.])
y: tensor([1., 1., 1.])
dot product of x and y: 3.0


In [ ]:
# Equivalently, we can calculate the dot product of two vectors by performing an elementwise multiplication followed by a sum
torch.sum(x * y)

tensor(3.)

In [41]:
A.shape, x.shape, torch.mv(A, x), A @ x

(torch.Size([2, 3]), torch.Size([3]), tensor([ 5., 14.]), tensor([ 5., 14.]))

# Matrix–Vector Products

In [43]:
print("A:", A)
print("x:", x)
A.shape, x.shape, torch.mv(A, x), A @ x

A: tensor([[0., 1., 2.],
        [3., 4., 5.]])
x: tensor([0., 1., 2.])


(torch.Size([2, 3]), torch.Size([3]), tensor([ 5., 14.]), tensor([ 5., 14.]))

# Matrix–Matrix Multiplication

In [47]:
B = torch.ones(3, 4)
print(f"B: {B} | shape: {B.shape}")
print(f"A: {A} | shape: {A.shape}")
torch.mm(A, B), A @ B

B: tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) | shape: torch.Size([3, 4])
A: tensor([[0., 1., 2.],
        [3., 4., 5.]]) | shape: torch.Size([2, 3])


(tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

In [ ]:
# Norms

In [48]:
# The method norm calculates the ℓ2 norm.
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [49]:
# the ℓ1 norm
torch.abs(u).sum()

tensor(7.)

In [50]:
# The Frobenius norm
torch.norm(torch.ones((4, 9)))

tensor(6.)

# Calculus