In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


# Introduction to tensors

## creating to tensors
Pytorch tensors are created using 'torch.Tensor()'

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# get tensor back as Pythin int
scalar.item()

7

In [13]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
# dimension is like number of square brackets ([)
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [15]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [16]:
MATRIX.ndim

2

In [20]:
MATRIX[1]

tensor([ 9, 10])

In [21]:
MATRIX.shape

torch.Size([2, 2])

In [23]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 7],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 7],
         [2, 4, 5]]])

In [24]:
TENSOR.ndim

3

In [25]:
TENSOR.shape # what is that mean?

torch.Size([1, 3, 3])

In [26]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 7],
        [2, 4, 5]])

<img src="https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png" alt="My image description" width="800" height="400">

<img src="https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-scalar-vector-matrix-tensor.png" alt="My image description" width="800" height="400">


| Name | What is it? | Number of dimensions | 	Lower or upper (usually/example) |
|---|---|---|---|
| scalar | 	a single number | 0 | 	Lower (a)|
| vector | 	a number with direction (e.g. wind speed) or list of numbers | 1 | Lower (y)|
| matrix | 	a 2-dimensional array of numbers | 2 | 	Upper (Q)|
| tensor | 	an n-dimensional array of numbers | 	n (0 = scalar, 1 = vector) | Usually Upper (T)|


## Random tensors

Why random tensors?
Random tensors are important becaue the way many neural networks learn is that they start with tensors with tensors full of random numbers and then adjust those random numbers to better represent the data.


`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

the rand is created random number between from 0 to 1

In [22]:
# create a random tensor of size (3, 4)
"""
(3, 4, 3)
Үүнийг дараах байдлаар төсөөлж болно:
3 ширхэг матриц
Матриц бүр 4 row, 3 column

tensor of size (3, 4)
3 row, 4 column

"""
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5723, 0.3248, 0.4374, 0.0722],
        [0.5176, 0.1872, 0.2894, 0.4936],
        [0.8290, 0.6524, 0.1556, 0.8673]])

In [20]:
random_tensor.ndim

5

In [24]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels(R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

<img src="https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-tensor-shape-example-of-image.png" alt="My image description" width="800" height="400">

## zeros and ones

In [26]:
# create a tensor of all zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## creating a range of tensors and tensors-like

In [ ]:
# use torch.arange()
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
torch.arange(start=0, end=100,step=10)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [34]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes
Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning

* Tensors not right datatype
* Tensors not right shape
* Tensors not on the right device

There are many types. 

In [35]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,          # what datatype is the tensor(e.g float32 or float16)
                               device=None,         # what device is your tensor on
                               requires_grad=False  # whether or not to track gradients with this tensors operations
                               )

In [36]:
float_32_tensor.dtype

torch.float32

## Manipulating tensors(tensor operations)
Tensor operation includes:
* Addition
* Subtraction
* Multiplication (elemet-wise)
* Division
* Matrix multiplication

In [39]:
# create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [41]:
# multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [42]:
# substract 10
tensor - 10 

tensor([-9, -8, -7])

In [44]:
# Try out PyTorch in-built functions
print("multiply=", torch.mul(tensor, 10))

multiply= tensor([10, 20, 30])


### Matrix multiplication
Two main ways of performing multiplication in neural networks and deep learning

* Element-wise multiplication
* Matrix multiplication (dot product)


In [47]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: { tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [48]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Matrix multiplication by hand
2:23