In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


# Introduction to tensors

## creating to tensors
Pytorch tensors are created using 'torch.Tensor()'

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [ ]:
# get tensor back as Pythin int
scalar.item()

7

In [13]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
# dimension is like number of square brackets
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [15]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [16]:
MATRIX.ndim

2

In [20]:
MATRIX[1]

tensor([ 9, 10])

In [21]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 7],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 7],
         [2, 4, 5]]])

In [24]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape # what is that mean?

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 7],
        [2, 4, 5]])

<img src="https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png" alt="My image description" width="800" height="400">

<img src="https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-scalar-vector-matrix-tensor.png" alt="My image description" width="800" height="400">


| Name | What is it? | Number of dimensions | 	Lower or upper (usually/example) |
|---|---|---|---|
| scalar | 	a single number | 0 | 	Lower (a)|
| vector | 	a number with direction (e.g. wind speed) or list of numbers | 1 | Lower (y)|
| matrix | 	a 2-dimensional array of numbers | 2 | 	Upper (Q)|
| tensor | 	an n-dimensional array of numbers | 	n (0 = scalar, 1 = vector) | Usually Upper (T)|


In [ ]:
# 1:35 you need to practice dimension 